###### """
1. Numpy is used to work with multidimentional arrays 
2. numpy array object is faster than list iun python 
3. it is called as ndarray
4. why faster ?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
5. to import numpy 
    import numpy as py 
"""
import numpy as np # linear algebra using alias as np
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
"""Lets define a 1d array in Numpy 
"""
arr=np.array([1,2,3,4,5])
print(arr)

#chekcing version of np 
print(np.__version__)

#checking type of this array 
print("type of array :",type(arr))

#checking data type in an array Shows data type of elements in an array 
print("Check data type with arr.dtype :",arr.dtype)


In [ ]:
#Can we use tuple to create a np array 
#let's try 
arr1=np.array((6,7,8))
print(type(arr),arr)

In [ ]:
"""Lets try 2d Array 
    2d array  will be list of list  
    shown with [[
"""
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Data type of array: ",arr.dtype)
print("size of array using len(arr) :",len(arr))
print(arr)

In [ ]:
"""Lets try 3d Array 
    2d array  will be list of list    
    shown witrh [[[
"""
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Data type of array: ",arr.dtype)
print("size of array using len(arr) :",len(arr))
print(arr)

In [ ]:
"""checking dimention with arr.ndim method 
returns an integer that tells us how many dimensions the array have.
"""
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print("Dimentions of 1D array a = a.ndim :",a.ndim)
print("Dimentions of 2D array b = b.ndim :",b.ndim)
print("Dimentions of 3D array c = c.ndim :",c.ndim)


In [ ]:
"""
higher dimentional array can specified and created 
"""
arr=np.array([1,2,3,4,5],ndmin =5)
print(arr)
print(arr.ndim)


In [ ]:
"""Access Array Elements indexing starts from '0' like list """ 

arr=np.array([1,2,3,4,5]) 
print("Accessing 1D array is simple as list : ", arr[0])

arr2d=np.array([[1,2,3],[4,5,6]]) 
print(arr2d) 
print("print :Accessing 2D array 2nd row 3rd column : ",arr2d[1,2])

arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
print(arr3d) 
print(" 3D array 3rd element of 2nd array of first array : ",arr3d[0,1,2])


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3] and: [4, 5, 6]

Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

In [ ]:
"""We can also use negative indexing """
arr2d=np.array([[1,2,3],[4,5,6]]) 
print(arr2d) 
print("print :Accessing last element for 2nd array  : ",arr2d[1,-1])

# **Array Slicing **
**[start:end:step]**

**start index : included **

**end index is excluded **

**step is optional** **


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

In [ ]:
#everything after 2nd index 
print(arr[2:])

#everything before 4th index 
print(arr[:4])

#negative slicing 
print(arr[-3:-1]) # should p[rint 5 and 6 as last index is excluded ]

#Return every other element from the entire array:
print(arr[::2])

In [ ]:
"""
Slicing 2-D Arrays
From the second element, slice elements from index 1 to index 4 (not included):
"""
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])
print(arr[0:2, 2])

"""
From both elements, 
slice index 1 to index 4 (not included),
this will return a 2-D array:
0:2 will give 0th location 1:4
1st location 1:4
"""
print(arr[0:2, 1:4])

In [ ]:
"""
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string

lets check array data type with dtype
"""
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)  #U - unicode string

arr = np.array(["apple", "banana"])
print(arr.dtype) 

# Creating Arrays With a Defined Data Type

# 

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

# Converting Data Type on Existing Arrays


In [ ]:
"""
The astype() function creates a copy of the array,
and allows you to specify the data type as a parameter.
"""
arr = np.array([1, 2, 3, 4], dtype='f')
newarr=arr.astype(int)
#newarr=arr.astype('i')
print(arr.dtype)
print(newarr.dtype)

In [ ]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

# The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

arr.copy()

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

arr.view()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
newarr=arr.copy()
print(newarr)
print(newarr.base) #doen not own data with base method 

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
newarr=arr.view()
arr[0]=10
print(arr)
print(newarr)
#both the view and original array changed 
print("---------------")
newarr[-1]=12
print(arr)
print(newarr)
print("-----Base method----------")
print(newarr.base)

# Shape of an Array
The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
"""
The example above returns (2, 4), which means that the array has 2 dimensions, 
where the first dimension has 2 elements and the second has 4.
"""

In [ ]:
"""
Create an array with 5 dimensions
using ndmin using a vector with values 1,2,3,4 
and verify that last dimension has value 4:
"""

arr=np.array([1,2,3,4],ndmin=5)
print(arr.shape)
print(arr[0,0,0,0,2])

# Reshaping arrays
By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr.shape)
print(newarr)

In [ ]:
newarr = arr.reshape(2, 2,3)
print(newarr.shape)
print(newarr)
print(newarr.base)  #return view original array 

In [ ]:
"""
numpy will calulate element in unknown dimention 

"""
newarr=arr.reshape(2,2,-1)
print(newarr)

# Flattening the arrays
convertung to 1 D array


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

# Iterating Arrays

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

In [ ]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

In [ ]:
"""
We can use op_dtypes argument and pass 
it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place 
(where the element is in array) so it needs some other space 
to perform this action, that extra space is called buffer,
and in order to enable it in nditer() we pass flags=['buffered'].
"""
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


In [ ]:
#Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

# Enumerated Iteration Using ndenumerate()
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [ ]:
arr = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

# NumPy Joining Array
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)  #change the axis and check 

print(arr)

# Joining Arrays Using Stack Functions


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)
arr = np.stack((arr1, arr2), axis=0)

print(arr)

In [ ]:
#Stacking Along Rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)
print("-------Stacking Along Columns--------")
#Stacking Along Columns
arr = np.vstack((arr1, arr2))
print(arr)
print("-------Stacking Along Height (depth)--------")
#Stacking Along Height (depth)
arr = np.dstack((arr1, arr2))
print(arr)
print(arr.base)  #copy not view 
for idx,x in np.ndenumerate(arr):
    print(idx,x)

# Splitting NumPy Arrays
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

In [ ]:
"""Splitting 2-D Arrays
Use the array_split() method,
pass in the array you want to split and the number of splits you want to do.
"""
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)

In [ ]:
"""Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

"""
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)
newarr = np.vsplit(arr, 3)

print(newarr)

# NumPy Searching Arrays
where method

In [ ]:
"""You can search an array for a certain value,
and return the indexes that get a match.

To search an array, use the where() method.
"""
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

# There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

In [ ]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# Sort() method

In [ ]:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

In [ ]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

In [ ]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# Generate Random Number
NumPy offers the random module to work with random numbers.


In [25]:
import numpy as np
from numpy import random


"""
The randint() method 
takes a size parameter where you can specify the shape of an array.
"""

x = random.randint(100)

print(x)

#create 1 d array 
x=random.randint(100,size=(5))
print(x)

#create 2d Array 
x=random.randint(1,1001,size=(3,8))
print(x)

30
[13 20 43  7 48]
[[670 948 443 491 978 967 240 559]
 [404 133  39 751 901 957 746 682]
 [757 456 406 513 137 635 243 555]]


In [27]:
#rand() method 
x=random.rand(5)
print(x)
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x=random.rand(3,5)
print(x)

[0.37006865 0.47353992 0.67489075 0.97279358 0.03700673]
[[0.63848584 0.99779592 0.40466949 0.68858829 0.49917472]
 [0.14550333 0.66373914 0.63885476 0.71027147 0.53127607]
 [0.52101769 0.86596467 0.08408455 0.55917159 0.74818819]]


# Generate Random Number From Array

In [34]:
"""The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.
"""

x=random.choice([3,7,9])
print(x)

#put any of these numbers in x array of size (3,5)
x=random.choice([3,7,9,12],size=(2,5))
print(x)

x=random.choice([3,7,9,12],size=(5))
print(x)

"""
Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0
"""
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print("----1D array with choice fiunction and probability with size 100 ----")
print(x)

3
[[3 3 3 9 7]
 [9 7 3 9 9]]
[12  7 12  3  9]
----1D array with choice fiunction and probability with size 100 ----
[5 7 7 3 7 5 7 7 3 7 7 7 7 5 7 7 5 5 5 7 7 3 5 7 3 7 7 7 5 7 7 7 7 7 5 5 7
 7 7 7 7 7 7 7 7 5 7 7 7 5 7 7 5 7 7 7 7 7 5 7 3 5 7 3 5 5 3 7 7 7 7 5 7 3
 5 7 7 7 7 7 5 7 7 3 7 7 7 7 7 5 3 7 7 5 5 5 7 5 7 7]


# Random Permutations

In [36]:
"""
Shuffling Arrays
Shuffle means changing arrangement of elements in-place. i.e. in the array itself.
"""

arr=np.array([1,3,6,9,10])
random.shuffle(arr)  #MAKE CHANGES TO ORIGINAL ARRAY 
print(arr)
print(random.permutation(arr))  #WORKS ON A COPY DO NOT CHANGE ORIGINALK ARRAY 

[ 6  1  3 10  9]
[ 9 10  1  6  3]


In [37]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[ 0.63630821  0.27604932  0.62468616]
 [-0.07906603 -1.05493032 -0.92902101]]


# Arithmatic operations 

In [56]:
x=np.array([1,2,3,4])
y=np.array([5,7,8,9])

z= np.sum([x,y])
print("SUm of add to one value : ",z)

z=np.add(x,y)
print("Addition of each dimention element : ",z)

z=np.subtract(x,y)
print("substraction : ",z)

z=np.multiply(x,y)
print("Multiplication : ",z)

z=np.divide(x,y)
print("Divide : ",z)

z=np.power(y,x)
print("Power of: ",z)

z=np.mod(x,y)
print("MOd of : ",z)

z=np.remainder(x,y)
print("Remonder of : ",z)
"""
Quotient and Mod
The divmod() function return both the quotient and the the mod. 
The return value is two arrays, 
the first array contains the quotient and second array contains the mod.
"""
z=np.divmod(x,y)
print("divmod of : ",z)

arr=np.array([-1,1,-2,-3])
print("Absolute of : ",np.absolute(arr))



SUm of add to one value :  39
Addition of each dimention element :  [ 6  9 11 13]
substraction :  [-4 -5 -5 -5]
Multiplication :  [ 5 14 24 36]
Divide :  [0.2        0.28571429 0.375      0.44444444]
Power of:  [   5   49  512 6561]
MOd of :  [1 2 3 4]
Remonder of :  [1 2 3 4]
divmod of :  (array([0, 0, 0, 0]), array([1, 2, 3, 4]))
Absolute of :  [1 1 2 3]


# Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

truncation
fix
rounding
floor
ceil

In [53]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])
print("trunc :",arr)

arr = np.fix([-3.1666, 3.6667])
print("fix :",arr)

arr = np.around(3.1666, 2)
print("around :",arr)

arr = np.floor([-3.1666, 3.6667])
print("floor :",arr)

arr = np.ceil([-3.1666, 3.6667])
print("ceil :",arr)

trunc : [-3.  3.]
fix : [-3.  3.]
around : 3.17
floor : [-4.  3.]
ceil : [-3.  4.]


In [60]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)
"""
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.
"""
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)

print(newarr)

[6 6]
[1 3 6]


# frompyfunc()

In [40]:
"""
The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.
"""

def myadd(x,y):
    return x+y
myadd=np.frompyfunc(myadd,2,1)
print(myadd(x,y))

[6 9 11 13]


In [4]:
import numpy as np
arr = np.random.randint(1, 101, 100).reshape(10, -1)
print(np.random.randint(1, 101, 100).reshape(10, -1))

[[37 12 51 66 75 64 81 86 74 16]
 [41 73 15 51 16 21 30 76 34 38]
 [48 79 64 34 45  4 21 86 17 73]
 [10 91 40 71 69  7 76 29  3 53]
 [99 73 97 19 27 59 65 33 82 93]
 [66 51  8  3 31 64 61 84 96 74]
 [64 35 16 46  7 75 48 10  5  9]
 [ 6 56 66 75 44 73 62 83 44 80]
 [ 4 54 25 16 19 37 78 52 50 37]
 [96 57 54 92 95 54 46 80  4 70]]


In [6]:
A = np.array([1, 2, 3])

B = A * 2
print(B)

[2 4 6]


In [7]:
matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

[1. 1. 1. 1.]


In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = A.T
print(B)

[[1 3]
 [2 4]]


In [9]:
A = np.array([1, 2, 3])
B= np.array([4, 5, 6])
print(np.multiply(A,B))

[ 4 10 18]


In [16]:
A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]
print(B)
print(np.argmax(A))

[20 30]
3


In [17]:
arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)

print(result)

15


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


In [ ]:
"Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

In [ ]:
Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.

In [ ]:
Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.all

In [ ]:
Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.



In [ ]:
Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.



In [ ]:
Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.



In [ ]:
Given the following NumPy code, predict the output of the code:



import numpy as np



A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

In [ ]:
Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.



In [ ]:
 Given the following NumPy code, predict the output of the code:



import numpy as np



A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]



print(B)

In [ ]:
Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.